---
- hosts: all
  become: yes
  become_user: root
  tasks:
      - name: Start and enable services
        service: name={{ item }}
                 state=started
                 enabled=yes
        with_items:
            - dhcpcd
            - NetworkManager
            - nptd
            - cronie
