---
- hosts: all
  vars_prompt:
      - name: root_pwd
        prompt: "Chosen root password"
        private: yes
        encrypt: "sha512_crypt"
        confirm: yes

      - name: user_pwd
        prompt: "Chosen user password"
        private: yes
        encrypt: "sha512_crypt"
        confirm: yes
  roles:
      #- system

- hosts: all
  become_user: "{{ username }}"
  become: yes
  roles:
      - user
      - deploy_config
