---
- include: yaourt.yml
  when: ansible_os_family == "Archlinux"

- name: Update repos
  shell: yaourt -Syyu --noconfirm

- name: Install packages
  shell: yaourt -S {{ item }} --noconfirm --needed
  when: ansible_os_family == "Archlinux"
  ignore_errors: True
  with_items:
    # Xorg
    - xorg-server
    - xorg-server-utils
    - xorg-xinit
    - xclip
    - xautolock

    # Virtualbox
    - virtualbox-guest-modules-arch

    # Utilies
    - xf86-input-synaptics
    - alsa-utils
    - networkmanager
    - network-manager-applet
    - sysstat
    - acpi
    - cronie
    - libnotify
    - dunst
    - xorg-xrandr
    - arandr
    - rxvt-unicode-256xresources
    - termite-git
    - htop

    # Dev utils
    - python-pip
    - zsh
    - vim
    - tmux
    - ack

    # Latex
    - texlive-most

    # Web and network
    - openssl
    - curl
    - wget
    - chromium
    - transmission-gtk

    # Desktop environment
    - i3-gaps
    - i3lock
    - i3blocks
    - rofi
    - unclutter
    - bc
    - compton

    # Theming
    - feh
    - scrot
    - imagemagick
    - otf-inconsolata-powerline-git
    - ttf-impallari-cabin-font
    - ttf-font-awesome
    - terminus-font
    - ephifonts-no-helvetica
    - lxappearance
    - arc-icon-theme-git
    - gtk-theme-arc

    # File tools
    - nautilus
    - nautilus-dropbox
    - evince
    - unzip
    - git
    - subversion

    # Multimedia
    - vlc
    - kodi

- name: Install fontconfig
  shell: yes | yaourt -S {{ item }} --noconfirm --needed
  when: ansible_os_family == "Archlinux"
  ignore_errors: True
  with_items:
    - fontconfig-infinality
    - freetype2-infinality

- name: Enable services
  service: name={{ item }}
           enabled=yes
  become: yes
  become_user: root
  with_items:
      - NetworkManager
      - cronie

- name: Setup Cron jobs
  become: yes
  become_user: root
  cron: name="Wallpaper"
        state=present
        minute="*/15"
        job="DISPLAY=:0.0 /home/{{ username }}/scripts/random_wallpaper.sh"
        user="{{ username }}"

- include: git.yml

- include: chsh.yml
