---
- name: Change root password
  user: name=root
        password={{ root_pwd }}
        state=present

- name: Create {{ username }} user account
  user: name={{ username }}
        password={{ user_pwd }}
        state=present

- name: Update sudoers file
  shell: sed -i 's/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/' /etc/sudoers

- name: Add {{ username }} to wheel group
  user: name={{ username }}
        groups=wheel
        append=yes
