---
- name: Install grub and os-prober packages
  pacman: name=grub,os-prober state=present

- name: Install Grub
  shell: grub-install {{ primary_disk }}

- name: Make grub config
  shell: grub-mkconfig -o /boot/grub/grub.cfg
