---
- name: TMUX | Link config file
  file: src={{ dotfiles_path }}/.tmux.conf
        dest=~/.tmux.conf
        state=link
        force=yes

- name: TMUX | Clone plugin manager
  git:  repo=https://github.com/tmux-plugins/tpm
        dest=~/.tmux/plugins/tpm

- name: TMUX | Start tmux server
  shell: tmux new-session -s tmp -d
  ignore_errors: yes

- name: TMUX | Install plugins
  shell: tmux run-shell ~/.tmux/plugins/tpm/bindings/install_plugins
