---
- name: XFILES | Link xinitrc
  file: src={{ dotfiles_path }}/.xinitrc
        dest=~/.xinitrc
        state=link
        force=yes

- name: XFILES | Link Xresources
  file: src={{ dotfiles_path }}/.Xresources
        dest=~/.Xresources
        state=link
        force=yes

- name: XFILES | Reload Xresources
  shell: xrdb ~/.Xresources
