---
- name: ROFI | Create rofi conf folder if absent
  file: path=/home/{{ username }}/.config/rofi
        state=directory
        owner="{{ username }}"

- name: ROFI | Copy rofi config
  file: src={{ dotfiles_path }}/rofi.rasi
        dest=/home/{{ username }}/.config/rofi/rofi.rasi
        state=link 
        force=yes
