---
- name: XFILES | Link xinitrc
  file: src={{ dotfiles_path }}/.xinitrc
        dest=~/.xinitrc
        state=link
        force=yes

- name: XFILES | Enable VBoxClient in xinitrc
  shell: sed -i 's|#/usr/bin/VBoxClient-all|/usr/bin/VBoxClient-all' {{ dotfiles_path }}/.xinitrc
  when: virtualmachine == True

- name: XFILES | Link Xresources
  file: src={{ dotfiles_path }}/.Xresources
        dest=~/.Xresources
        state=link
        force=yes
